 language: node_js
 node_js:
   - "0.11"
   - "0.10"
   - "0.8"
 branches:
 only:
  - master
 notifications:
  email:
   - joaquim.serafim@gmail.com
 before_install:
   - npm install -g npm@~1.4.6
 script: npm test
